#!/usr/bin/env python3
"""Contact sheets for naming the game's numbered object kinds.

The game names none of its objects, so what a kind *is* has to be argued from
where it sits. This writes one section per (kind, type): how often it is
placed, which levels place it, whether a level ever gets more than one, what
its fields hold, and what sits on the blocks around it.

    python3 tools/kula_kinds.py            # out/kinds.md
    python3 tools/kula_kinds.py --kind 30  # just that kind, to stdout
"""
import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from kula_disc import open_disc, packs
from kula_level import Level, START_KIND
from kula_pak import Pak

OUT = Path(__file__).resolve().parent.parent / "out" / "kinds.md"
NEIGHBOURS = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]


def collect(disc):
    levels = []
    for theme, path in packs(disc):
        pak = Pak(disc.read_file(path), path)
        for i in range(len(pak)):
            levels.append(Level(pak.level(i), pak.name(i), theme))
    return levels


def report(levels, only=None):
    seen = defaultdict(lambda: {"total": 0, "levels": [], "fields": defaultdict(Counter),
                                "around": Counter(), "themes": Counter()})
    for L in levels:
        cells = {(c[0], c[1], c[2]): c[3] for c in L.cells}
        here = Counter()
        for ents in L.records:
            for e in ents:
                key = (e.kind, e.type)
                here[key] += 1
                s = seen[key]
                s["total"] += 1
                s["themes"][L.theme] += 1
                for i, v in enumerate(e.f):
                    if v != -1:
                        s["fields"][f"f{i + 5}"][v] += 1
                for dx, dy, dz in NEIGHBOURS:
                    p = (e.x + dx, e.y + dy, e.z + dz)
                    s["around"]["block" if p in cells else "air"] += 1
        for key, n in here.items():
            seen[key]["levels"].append((L.name, n))

    out = []
    for key in sorted(seen, key=lambda k: -seen[k]["total"]):
        if only is not None and key[0] != only:
            continue
        kind, typ = key
        s = seen[key]
        n_levels = len(s["levels"])
        once = sum(1 for _, n in s["levels"] if n == 1)
        out.append(f"## kind {kind} / type {typ}\n")
        if kind == START_KIND:
            out.append("The record every level ends with: start, look-at, angles, time.\n")
        out.append(f"- placed **{s['total']}** times across **{n_levels}** levels"
                   f"{', never more than once' if once == n_levels else f', exactly once in {once}'}\n")
        out.append(f"- worlds: {', '.join(f'{t}x{n}' for t, n in s['themes'].most_common())}\n")
        air = s["around"]["air"]
        blk = s["around"]["block"]
        out.append(f"- neighbours: {blk} block, {air} air "
                   f"({100 * blk / max(1, blk + air):.0f}% enclosed)\n")
        for f, c in sorted(s["fields"].items(), key=lambda kv: int(kv[0][1:])):
            vals = ", ".join(f"{v}x{n}" for v, n in c.most_common(6))
            out.append(f"- `{f}`: {vals}\n")
        sample = ", ".join(f"{nm}{'' if n == 1 else f' x{n}'}" for nm, n in s["levels"][:10])
        out.append(f"- levels: {sample}{' ...' if n_levels > 10 else ''}\n\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--disc", default=None)
    ap.add_argument("--kind", type=int, default=None)
    args = ap.parse_args()
    levels = collect(open_disc(args.disc))
    text = report(levels, args.kind)
    if args.kind is not None:
        print(text)
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f"# Object kinds in Kula World\n\n"
                   f"Generated by `tools/kula_kinds.py`; names go in "
                   f"`public/annotations.json`, not here.\n\n{text}")
    print(f"{OUT} written")


if __name__ == "__main__":
    main()
