#!/usr/bin/env python3
"""Contact sheets for naming the game's numbered objects and record kinds:
where each is placed, what its fields hold and what sits around it.

    python3 tools/kula_kinds.py            # out/kinds.md
    python3 tools/kula_kinds.py --type 30  # just that type, to stdout
    python3 tools/kula_kinds.py --kind 8   # just that record kind
"""
import argparse
import sys
from collections import Counter, defaultdict
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from kula_disc import open_disc, packs
from kula_level import FIELD_WORD, PAYLOAD_KINDS, UNPLACED_KIND, Level
from kula_pak import Pak

OUT = Path(__file__).resolve().parent.parent / "out" / "kinds.md"
NEIGHBOURS = [(1, 0, 0), (-1, 0, 0), (0, 1, 0), (0, -1, 0), (0, 0, 1), (0, 0, -1)]
FACE = ["-z", "+x", "+y", "-y", "-x", "+z"]


def collect(disc):
    levels = []
    for theme, path in packs(disc):
        pak = Pak(disc.read_file(path), path)
        for i in range(len(pak)):
            levels.append(Level(pak.level(i), pak.name(i), theme))
    return levels


def things(L):
    """(key, cell, fields, face) for each object and each record that is its own thing."""
    for r in L.records:
        if r.kind in PAYLOAD_KINDS or r.kind == UNPLACED_KIND:
            yield ("kind", r.kind), r.cell, r.f, None
        for o in r.objects:
            yield ("type", o.type), r.cell, o.f, o.face


def report(levels, only=None):
    seen = defaultdict(lambda: {"total": 0, "levels": [], "fields": defaultdict(Counter),
                                "around": Counter(), "themes": Counter(), "faces": Counter()})
    for L in levels:
        cells = {(c[0], c[1], c[2]): c[3] for c in L.cells}
        here = Counter()
        for key, cell, fields, face in things(L):
            here[key] += 1
            s = seen[key]
            s["total"] += 1
            s["themes"][L.theme] += 1
            if face is not None:
                s["faces"][face] += 1
            for i, v in enumerate(fields):
                if v != -1:
                    s["fields"][f"f{i + FIELD_WORD}"][v] += 1
            for dx, dy, dz in NEIGHBOURS:
                p = (cell[0] + dx, cell[1] + dy, cell[2] + dz)
                s["around"]["block" if p in cells else "air"] += 1
        for key, n in here.items():
            seen[key]["levels"].append((L.name, n))

    out = []
    for key in sorted(seen, key=lambda k: -seen[k]["total"]):
        if only is not None and key != only:
            continue
        what, num = key
        s = seen[key]
        n_levels = len(s["levels"])
        once = sum(1 for _, n in s["levels"] if n == 1)
        out.append(f"## {what} {num}\n")
        out.append(f"- placed **{s['total']}** times across **{n_levels}** levels"
                   f"{', never more than once' if once == n_levels else f', exactly once in {once}'}\n")
        out.append(f"- worlds: {', '.join(f'{t}x{n}' for t, n in s['themes'].most_common())}\n")
        if s["faces"]:
            out.append("- faces: " + ", ".join(f"{FACE[j]}x{n}" for j, n in sorted(s["faces"].items())) + "\n")
        air = s["around"]["air"]
        blk = s["around"]["block"]
        out.append(f"- neighbours: {blk} block, {air} air "
                   f"({100 * blk / max(1, blk + air):.0f}% enclosed)\n")
        for f, c in sorted(s["fields"].items(), key=lambda kv: int(kv[0][1:])):
            vals = ", ".join(f"{v}x{n}" for v, n in c.most_common(6))
            out.append(f"- `{f}`: {vals}\n")
        sample = ", ".join(f"{nm}{'' if n == 1 else f' x{n}'}" for nm, n in s["levels"][:10])
        out.append(f"- levels: {sample}{' ...' if n_levels > 10 else ''}\n\n")
    return "".join(out)


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--disc", default=None)
    ap.add_argument("--type", type=int, default=None, help="one object type, to stdout")
    ap.add_argument("--kind", type=int, default=None, help="one record kind, to stdout")
    args = ap.parse_args()
    levels = collect(open_disc(args.disc))
    only = ("type", args.type) if args.type is not None else ("kind", args.kind) if args.kind is not None else None
    text = report(levels, only)
    if only:
        print(text)
        return
    OUT.parent.mkdir(parents=True, exist_ok=True)
    OUT.write_text(f"# Objects and record kinds in Kula World\n\n"
                   f"Generated by `tools/kula_kinds.py`; names go in "
                   f"`public/annotations.json`, not here.\n\n{text}")
    print(f"{OUT} written")


if __name__ == "__main__":
    main()
